### ISSUE TITLE
Delay when changing keyboard layout

### ISSUE THREAD

**Issue by marcelogdeandrade** [elementary/switchboard-plug-keyboard#172] opened 2018-08-08 20:28 UTC
When changing from English (US) to Portuguese (Brazil) it takes a couple of seconds, freezing the system while doing it. It doesn't take as long if with English(US) to English(UK), but the delay is still noticeable.

Happened Elementary 5.0 Juno Beta

**Comment by mkinitcpio** [comment] 2018-08-21 19:33
I have the same problem.

**Comment by marcelogdeandrade** [comment] 2018-10-02 02:11
I'm trying to figure out where the delay is coming from, but still with no success.

My first hypothesis are:

- The usage of Glib.Settings. I have no experience with this lib, so I don't know the overhead of using it.
- A bug from this gnome version. I`ve seen some threads, like [this one](https://stackoverflow.com/questions/14172068/slow-keyboard-layout-switching-in-gnome-3-6), complaining about keyboard layout delay.

If someone that has more experience with Vala libs and this project can help me, I can try to fix it.

**Comment by unameisfine** [comment] 2018-10-19 09:32
This bug remained in the Juno release. It's terrible!

Related bugs:
https://github.com/elementary/wingpanel-indicator-keyboard/issues/43
https://github.com/elementary/gala/issues/220
https://github.com/elementary/switchboard-plug-keyboard/issues/59

**Comment by unameisfine** [comment] 2018-10-21 14:29
One method to fix this trouble:
`sudo dpkg-reconfigure keyboard-configuration`

and select keys combination to change layout,  that are not used in other combinations. If key used in another keyboard combination, combination gets slow.

**Comment by ktullanux** [comment] 2018-10-22 11:35
combination Shift+Shift change layout without delay

**Comment by vaclavhlobil** [comment] 2018-10-22 20:29
Switching EN <-> CZ with both Shifts has delay too. It's about 1 sec. Still affects "writer's flow". Anoying.

**Comment by unameisfine** [comment] 2018-10-23 09:02
> combination Shift+Shift change layout without delay

Do you know a way to change this combination to another?

**Comment by eljefuri** [comment] 2018-11-10 05:58
Chiming in to confirm annoyance at this.

**Comment by drequivalent** [comment] 2018-11-15 12:19
https://www.youtube.com/watch?v=_pKLKh0M4Js

**Comment by vaclavhlobil** [comment] 2018-11-15 13:03
Same here as in @drequivalent's video, but for cs <-> en layouts, switched with both Shifts. It's very annoying, especially when you type code mixed with national characters. I offten have to stop writting, delete last text written with wrong layout, and rewrite it with the right layout. Or return to bad signs and fix it. >:(

**Comment by unameisfine** [comment] 2018-11-15 14:12
> Same here as in @drequivalent's video, but for cs <-> en layouts, switched with both Shifts. It's very annoying, especially when you type code mixed with national characters. I offten have to stop writting, delete last text written with wrong layout, and rewrite it with the right layout. Or return to bad signs and fix it. >:(

However strange it may sound, but both shifts switch fast only if alt + shift method selected in system settings.

**Comment by peteruithoven** [comment] 2019-02-11 13:43
I'm closing this as a duplicate of https://github.com/elementary/gala/issues/220

**Closed by peteruithoven** 2019-02-11 13:43 UTC
