### ISSUE TITLE
Custom keyboard input area box has dark borders

### ISSUE THREAD

**Issue by D0J0P** [elementary/switchboard-plug-keyboard#382] opened 2021-08-31 23:00 UTC
## What Happened

See photos below. The border area for custom keyboard list is really dark and thick compared to other lists in the OS where you can add and remove stuff

![Screenshot from 2021-08-31 18 51 33](https://user-images.githubusercontent.com/19495660/131586263-ff2d7f3f-18b1-4139-926e-b9969d454c7e.png)

Box list on the left looks normal:
![Screenshot from 2021-08-31 18 55 59](https://user-images.githubusercontent.com/19495660/131586463-aad98fbc-4820-4da4-86f6-9e185feafd5f.png)

## Expected Behavior

That it would look like other list boxes in the OS.

## Steps to Reproduce

1.
2.
3.

## Platform Information

elementary OS 6 Odin

**Comment by ryonakano** [comment] 2023-08-05 10:33
Closing because I can no longer reproduce this; maybe fixed by #373?

**Closed by ryonakano** 2023-08-05 10:33 UTC
