### ISSUE TITLE
Adding Fingerprint Login

### ISSUE THREAD

**Issue by neluckoff** [elementary/switchboard-plug-keyboard#409] opened 2022-05-18 20:06 UTC
### Problem

I have a laptop on which I really wanted to use your operating system, but there is a main problem - my laptop has the ability to log in with a fingerprint, but the system does not have such a setting.

### Proposal

As a suggestion, I'd like to suggest adding this feature by default. I tried to install the ubuntu repository to use my finger as a login, but it didn't work for me.

**Comment by danrabbit** [comment] 2022-05-18 20:15
Closing as a duplicate of https://github.com/elementary/switchboard-plug-security-privacy/issues/117

**Closed by danrabbit** 2022-05-18 20:15 UTC
