### ISSUE TITLE
Overlapping text when changing accelerator

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/switchboard-plug-keyboard#375] opened 2021-08-05 05:47 UTC
## What Happened
When trying to change a shortcut, the text showing the current shortcut or "Disabled" isn't replaced with "New accelerator", but overlapped
![Screenshot from 2021-08-05 05 37 54](https://user-images.githubusercontent.com/13716824/128297375-f6e73e0b-baa6-493b-9985-be763d562713.png)

## Expected Behavior
In Hera (and presumably the intended behaviour) the existing text is hidden while making a new shortcut.

## Steps to Reproduce

1. Attempt to change a shortcut

## Platform Information
Odin RC

**Comment by ryonakano** [comment] 2021-08-05 06:14
Closing as a duplicate of #357.

**Closed by ryonakano** 2021-08-05 06:14 UTC
