### ISSUE TITLE
Keyboard shortcuts of application and media stops working

### ISSUE THREAD

**Issue by OssNass** [elementary/switchboard-plug-keyboard#318] opened 2020-08-25 19:57 UTC
I am using elementary OS Hera, and sometimes media shortcuts stops working with VLC, but they return to normal when logging out then back in.

But the bigger problem is when the application shortcuts (terminal, web browser,file browser) stops working and can work only be reassigning the shortcut keys

**Comment by lenemter** [comment] 2024-02-17 12:58
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2024-02-17 12:58 UTC
