### ISSUE TITLE
Assigning a shortcut displays texts one on another

### ISSUE THREAD

**Issue by Loreno10** [elementary/switchboard-plug-keyboard#369] opened 2021-07-10 13:33 UTC
## What Happened
Whenever I want to assign a new shortcut, there are two texts displayed - one on another - the old shortcut and "New accelerator". I'd post a screenshot, but for some reason GitHub says that my file is empty :\

## Expected Behavior
Just one text displayed - "New accelerator" (although something like "New shortcut" sounds more natural to me)

## Steps to Reproduce
Try to change any of the shortcuts

## Platform Information
This issue can be seen on both eOS 5.1.7 and eOS 6 Beta 2

**Comment by Loreno10** [comment] 2021-07-10 16:03
I'd like to try to fix this myself. However, I do not now how to run the plug locally. I run the commands that README says to run (meson...., ninja, ninja install), but I have no idea what to do next.

**Comment by jeremypw** [comment] 2021-07-12 08:24
This is a duplicate of #357.

**Closed** 2021-07-12 12:00 UTC
