### ISSUE TITLE
Make "switch layout" shortcut empty by default

### ISSUE THREAD

**Issue by otavioschwanck** [elementary/switchboard-plug-keyboard#260] opened 2019-11-14 14:43 UTC
The switch window function (alt + shift + tab) doen't work because the shortcut to switch layout is alt + shift.

On emacs, the Alt + shit + > doent't work.

I take long time to figure it out why this functions doen't work.

**Comment by emkis** [comment] 2019-12-05 12:43
On my notebook, it even freezes the screen for a few seconds because of this bug.

To fix this bug here, i just disabled the **switch layout**.

**Comment by lenemter** [comment] 2023-08-17 11:12
Closing as duplicate of https://github.com/elementary/gala/issues/1261.

**Closed by lenemter** 2023-08-17 11:12 UTC
