### ISSUE TITLE
KEYBOARD

### ISSUE THREAD

**Issue by igormachado** [elementary/switchboard-plug-keyboard#344] opened 2021-01-15 15:49 UTC
AFTER LAST UPDATE ME KEYBOARD LAYOUT ENGLISH(US,ALT.INT) DOES NOT WORK WELL. EX:  ~a != ã  shift+~+a does not work and shift+^+e does not work too.

**Comment by santileortiz** [comment] 2021-01-16 05:54
It may be related to #343. Are you using elementary OS Hera?.

Can you install dconf-editor (`sudo apt-get install dconf-editor`) and use it to navigate to `org.gnome.desktop.input-sources`. What's the value for the `sources` key?.

**Comment by lenemter** [comment] 2024-01-18 03:03
Closing because the issue is old. If you still encounter it, please reply here.

**Closed by lenemter** 2024-01-18 03:03 UTC
