### ISSUE TITLE
Volume media keys do not work after trying to assign a shortcut

### ISSUE THREAD

**Issue by baragatti** [elementary/switchboard-plug-keyboard#180] opened 2018-10-25 17:59 UTC
After going to shortcut and set volume up to the media key of volume up, the key displays "Disabled" and the volume up media key stops working.

Steps to reproduce:
Settings > Keyboard > Shortcuts > Media > Try to set the volume up media key to "Volume up" option.

After doing this, the option shows as disabled as the volume up keys stops working.

How to fix volume keys (manual solution):
https://elementaryos.stackexchange.com/a/12169

**Comment by peteruithoven** [comment] 2018-10-25 20:04
Thanks for the report! I'mafraid this is actually a duplicate of https://github.com/elementary/switchboard-plug-keyboard/issues/29

**Closed by peteruithoven** 2018-10-25 20:04 UTC
Labels: Status: Duplicate
