### ISSUE TITLE
Keyboard stops working

### ISSUE THREAD

**Issue by Prince-741152** [elementary/switchboard-plug-keyboard#289] opened 2020-05-14 13:35 UTC
I'm using Dell Inspiron 15-3555

Whenever I'm turning the brightness to full, the keyboard stops working... Until I restart my Laptop using mouse/touchpad, the keyboard stays unresponsive.

**Comment by lenemter** [comment] 2023-08-17 11:22
Closing because the issue is old and no similar reportes was filed. If you still encounter this issue, please open a new issue.

**Closed by lenemter** 2023-08-17 11:22 UTC
