### ISSUE TITLE
When assigning new accelerator, new text appears over existing text and both are visible

### ISSUE THREAD

**Issue by abodedis** [elementary/switchboard-plug-keyboard#380] opened 2021-08-18 14:49 UTC
## What Happened
When assigning a new accelerator, the "New Accelerator..." text appears over the existing text of the current keyboard shortcut and both texts are visible simultaneously.

## Expected Behavior
"New Accelerator" text should not overlap existing text.

## Steps to Reproduce
Go to Settings-> Keyboard
Attempt to assign a new accelerator to any of the functions.
"New Accelerator" appears over the existing text and both texts are visible simultaneously.

## Platform Information
OS: elementary OS 6 Odin x86_64 
Kernel: 5.11.0-27-generic 
Packages: 1699 (dpkg), 20 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel Xeon W3680 (12) @ 3.326GHz 
GPU: NVIDIA GeForce GT 1030 
Memory: 1370MiB / 24047MiB

**Comment by ryonakano** [comment] 2021-08-18 15:03
Duplicate of #357.

**Closed** 2021-08-18 15:03 UTC
