### ISSUE TITLE
Media keyboard keys disabled when editing Keyboard Shortcuts in Juno 5.0

### ISSUE THREAD

**Issue by cdmatter** [elementary/switchboard-plug-keyboard#179] opened 2018-10-19 17:32 UTC
My Dell XPS 13 has a the standard play/pause, next track, previous track keys on the keyboard.  If I go into the Keyboard Shortcuts section in the System Settings application and edit any of the Play, Previous Track, Next Track keys listed under Media, the play/pause, next track, previous track keys on the keyboard no longer seem to work.  Even if I clear the custom shortcut, these media keys will not work.  Right now, both the play/pause and next track keys on the keyboard are not functioning after I edited the keyboard shortcuts for them.  However, the previous track does still work because I have never edited this shortcut, so this issue seems repeatable.  I do not want to do further testing in case I lose additional keyboard shortcut functionality.  My next step is to see if this problem persists across logout/restart.

**Comment by peteruithoven** [comment] 2018-10-19 17:37
I'm afraid this is a duplicate of: https://github.com/elementary/switchboard-plug-keyboard/issues/29

**Closed by peteruithoven** 2018-10-19 17:37 UTC
