### ISSUE TITLE
The shortcut key Alt+Shift to switch keyboard layouts conflicts in Gravit Designer

### ISSUE THREAD

**Issue by iamdenver** [elementary/switchboard-plug-keyboard#269] opened 2019-12-09 07:54 UTC
Hi! When I'm holding Alt+Shift keys to scale that rectangle proportionally, it wouldn't do a thing within the editor, but switches input language. Alt+Shift is a great combination for both, but I would use them on Windows with never an issue.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/58046850/70417470-fa36b900-1a69-11ea-8fb9-0933b2bdd729.gif)

**Comment by ryonakano** [comment] 2020-02-07 21:43
![2020-02-08 06 41 00 のスクリーンショット](https://user-images.githubusercontent.com/26003928/74068071-01644e00-4a3e-11ea-8e0f-c29e549a3139.png)

Did you try changing the shortcut key `Alt+Shift` that is used to switch keyboard layouts in elementary OS?

**Comment by nguyenkien** [comment] 2020-06-06 05:23
Ask gravit develop to fix this

**Comment by lenemter** [comment] 2023-08-17 11:12
Closing as duplicate of https://github.com/elementary/gala/issues/1261.

**Closed by lenemter** 2023-08-17 11:12 UTC
