### ISSUE TITLE
XF86AudioPrev and XF86AudioNext work on any random application, and not the one that is currently playing music.

### ISSUE THREAD

**Issue by subnut** [elementary/switchboard-plug-keyboard#396] opened 2022-01-13 07:19 UTC
### What Happened?

Say you have three applications open -
1. `io.elementary.Music` (**Paused**)
2. Firefox (**Paused**)
3. Spotify (**Playing**)

If you use `XF86AudioNext`, you would expect it to act upon Spotify. But it acts on Firefox instead!

### Steps to Reproduce

See **What Happened?**

### Expected Behavior

Make `XF86AudioNext` and `XF86AudioPrev` affect the applications that are currently _playing_ media.

If no application is currently playing media, then make it act on the most-recently-playing application (_à la_ Microsoft Windows)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-10-21 04:13
Unfortunately, I cannot reproduce the issue, probably got fixed in OS 7. If you still encounter it, please file a new issue upstream https://gitlab.gnome.org/GNOME/gnome-settings-daemon

**Closed by lenemter** 2023-10-21 04:13 UTC
