### ISSUE TITLE
Printscreen button can't be configured

### ISSUE THREAD

**Issue by wout** [elementary/switchboard-plug-keyboard#440] opened 2023-03-26 08:52 UTC
### What Happened?

I always reconfigure the print screen button to trigger "copy area to clipboard" instead of "grab the whole screen". That worked with previous elementary versions but in version 7, no more. Only combinations are registered in the shortcuts panel, not the print button alone.

### Steps to Reproduce

1. Go to Settings > Keyboard > Shortcuts > Screenshots
2. Disable "Grab the whole screen"
3. Click on the shortcut for "Copy an area to clipboard" to activate key registration
4. Hit the print screen button on the keyboard

### Expected Behavior

Hitting the print screen button should register the button, but nothing happens. Only is another  key is included too the combination is registered.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

![image](https://user-images.githubusercontent.com/107324/227765356-2495b0d8-e740-4dab-ba10-113c8f708c4d.png)

**Comment by ryonakano** [comment] 2023-08-05 10:38
Closing as duplicate of #440

**Closed by ryonakano** 2023-08-05 10:38 UTC

**Comment by wout** [comment] 2023-08-05 12:23
@ryonakano This is #440 🤓️.

**Comment by ryonakano** [comment] 2023-08-05 12:31
Oops, sorry I meant #430. :see_no_evil:

Anyways, it should be now fixed in #457.
