### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by rahidulislam** [elementary/switchboard-plug-keyboard#254] opened 2019-10-17 13:13 UTC
Keyboard Layout does not add
![Screenshot from 2019-10-17 19 12 57](https://user-images.githubusercontent.com/33887458/67011866-2ee55e80-f112-11e9-99e8-4740a3fb16b2.png)

**Comment by lenemter** [comment] 2023-08-17 11:05
Closing because reporter didn't provide sufficient information or steps to reproduce.

**Closed** 2023-08-17 11:05 UTC
Labels: Status: Incomplete
