### ISSUE TITLE
Slowly switch languages via hotkey

### ISSUE THREAD

**Issue by andaran** [elementary/switchboard-plug-keyboard#351] opened 2021-04-05 18:53 UTC
Languages are switched slowly via hotkey. In my case, it takes a long time to switch from Russian to English, vice versa a little faster. The problem appears on the host and virtual machine, as well as many other users.

**Comment by ryonakano** [comment] 2021-04-05 23:47
Hi, thank you for your reporting. Is your issue the same with elementary/gala#220? I feel it's similar.

**Comment by andaran** [comment] 2021-04-06 15:07
> Hi, thank you for your reporting. Is your issue the same with [elementary/gala#220](https://github.com/elementary/gala/issues/220)? I feel it's similar.

Yes, the problem is the same. This script helped https://github.com/yamnikov-oleg/switch-layout.

As I understand it, this is not an elementary problem, but a gnome. In any case, I would like to have a solution out of the box. Thanks.

**Comment by ryonakano** [comment] 2021-04-06 23:35
Thank you for your reply, I'm closing the issue as a duplicate of elementary/gala#220.

**Closed by ryonakano** 2021-04-06 23:35 UTC
