### ISSUE TITLE
[Odin] Superposition of text

### ISSUE THREAD

**Issue by kdwk** [elementary/switchboard-plug-keyboard#367] opened 2021-06-11 07:01 UTC
## What Happened

In the shortcuts tab, when setting a new accelerator for a shortcut, 'New accelerator...' and the old accelerator is imposed on each other.

## Expected Behavior

Only shows 'New accelerator...'

## Steps to Reproduce

1. Open System Settings
2. Go to Keyboard-> Shortcuts
3. Set a new accelerator for a shortcut

**Comment by ryonakano** [comment] 2021-06-11 07:03
Thank you for your reporting, but closing as a duplicate of #357

**Closed by ryonakano** 2021-06-11 07:03 UTC
