### ISSUE TITLE
All keyboard shortcuts will be reset after the update

### ISSUE THREAD

**Issue by qtskorea** [elementary/switchboard-plug-keyboard#271] opened 2020-02-14 01:24 UTC
Hi. 

When the system update is complete, all the meccos that I set up are reset I have to set it up again after the update. to say that... 

I run the terminal by pressing ctrl key +alt key + T. However, after updating the system, the setting disappears. I have set up a lot of other macros, and they all disappear. 

The macro of the user settings in the bottom list still works. I hope these settings will work even after the system updates. 

with respect and gratitude Your big fan in South Korea.

**Comment by lenemter** [comment] 2024-03-18 08:06
Closing because the issue is old and seems to be resolved.

**Closed by lenemter** 2024-03-18 08:06 UTC
