### ISSUE TITLE
Removing a selected custom shortcut with "-" button very difficult

### ISSUE THREAD

**Issue by ianmjones** [elementary/switchboard-plug-keyboard#371] opened 2021-07-20 19:33 UTC
## What Happened

Clicking the "-" button to remove the currently selected custom shortcut does nothing.

In the below screenshot, after clicking into the shortcut's name, I've clicked the enabled "-" button at the bottom but the shortcut remains.

![Screenshot from 2021-07-20 20-11-34@2x](https://user-images.githubusercontent.com/4710/126383378-ddb1f02a-d26f-4328-81a2-a61217fb7f16.png)

I can click that "-" button as many times as you like, that shortcut isn't going anywhere!

However, if I click into the shortcut's new key stroke field and hit Escape so that the entire shortcut line is highlighted, then I can remove the shortcut with the "-" button.

When I took the following screenshot the blue highlight turned grey, but the difference between it's full line being highlighted (which allows removal) and the previous screenshot's field only highlight is still visible.

![Screenshot from 2021-07-20 20-12-12@2x](https://user-images.githubusercontent.com/4710/126384095-1f376541-de8c-4e8c-9d8d-cf75d6375d59.png)

## Expected Behavior

When I've clicked anywhere on a custom shortcut I'd expect click the "-" button to remove that shortcut.

## Steps to Reproduce

1. Click into an existing custom shortcut's command string.
2. Click the "-" button at the bottom of the pane to remove the shortcut.
3. The shortcut is not removed.

### Logs

N/A

## Platform Information

elementary 6 beta 2, fully updated as of 20:00 BST (19:00 UTC) 2021-07-20.

**Comment by jeremypw** [comment] 2021-07-23 16:01
Thanks for reporting but I think this is essentially a duplicate of #275

**Comment by jeremypw** [comment] 2021-07-23 16:02
Closing as duplicate - please feel free to re-open if you think it differs.

**Closed by jeremypw** 2021-07-23 16:02 UTC
Labels: Status: Duplicate

**Comment by ianmjones** [comment] 2021-07-23 16:06
Doh, I even used a very similar title! :facepalm: 

My search skills are clearly lacking. :disappointed:
