### ISSUE TITLE
[odin-beta] When Reassigning Keys, "New Accelerator" and Old Key Combination Overlaps

### ISSUE THREAD

**Issue by GlasierXplor** [elementary/switchboard-plug-keyboard#362] opened 2021-05-13 08:43 UTC
## What Happened

In the keyboard shortcuts menu, when reassigning shortcuts, the "New Accelerator" text will overwrite the original text before clicking on it.
![1](https://user-images.githubusercontent.com/25283178/118100533-25fd6180-b409-11eb-9f0a-534f61428c5c.png)

## Expected Behavior

The "New Accelerator" should be on its own

## Steps to Reproduce

1. Open System Settings > Keyboard > Shortcuts
2. Reassign any shortcuts
3. Notice that "New Accelerator" will overlap the original text below.

### Logs

Here is the only thing printed by the terminal, but unsure if this affects the issue.
![Screenshot from 2021-05-13 16-40-15](https://user-images.githubusercontent.com/25283178/118101209-ee42e980-b409-11eb-8238-4c1842d47f64.png)

## Platform Information

- `elementaryos-6.0-daily.20210430.iso` (latest updates as of 13 May 2021 UTC+08)
- VMware Player 15

**Comment by jeremypw** [comment] 2021-05-13 15:28
@GlasierXplor Thanks for taking the trouble to report this.  It is a duplicate of #357 so will close as such.

**Closed by jeremypw** 2021-05-13 15:28 UTC
