### ISSUE TITLE
Attempting to customize keyboard shortcuts results in reproducible crash

### ISSUE THREAD

**Issue by mkayen** [elementary/switchboard-plug-keyboard#122] opened 2018-01-23 15:31 UTC
I have a keyboard with no super key, but would like to move between workspaces. The following steps results in a crash.

(1) System Settings > Keyboard > Shortcuts > Workspaces 
(2) Press any setting (like "Switch to workspace 1") 
(3) Notice settings menu freezes. No applications can be pressed, even though mouse continues to be controllable. 
(4) Pressing the powerbutton on the machine seems to restore settings back to normal, however the setting changes to disabled.

Screenshot of what seems like relevant portions of the System Logs based on timing and reported failures:

![](https://i.stack.imgur.com/eS3T0.png)

Screenshot of System Settings screen:

![](https://i.stack.imgur.com/5Qh3V.png)

Thoughts on how to resolve? Thanks!

**Comment by J0Ar** [comment] 2020-01-03 00:13
I am a little late at this Issue-report but i noticed another problem and so i came here…

I am not sure this is a freeze/crash of the application or the system itself…I think the system is waiting for user input at the point where you click on ''Switch to workspace 1'' 

At this point where the system seems to freeze, you can probably press `[ESC]`

**Comment by pedropaulosuzuki** [comment] 2021-10-01 13:51
I can confirm this issue on elementaryOS 6.0 Odin. I cannot even open the applications menu while waiting for an input. Mouse movement works, but mouse click does not.

**Comment by jeremypw** [comment] 2021-10-05 11:37
When you click on one of the actions with shortcut (e.g. Switch to workspace 1) the system is put in a state where it is waiting for you to press the key combination desired for the new shortcut.  This appears to freeze the system but pressing `Esc` should release the grab and the system should then operate normally.  This is what happens for me. I agree that there does not seem to be an obvious reason why the mouse should be grabbed though.  Clicking anywhere should release the keyboard grab and the click processed normally.  Need to look into the code to see if there is a technical reason why this is not possible.  I think it should also be made clearer that the system is waiting for you to enter a new shortcut.

**Comment by lenemter** [comment] 2023-08-17 11:15
Closing in favor of https://github.com/elementary/switchboard-plug-keyboard/issues/264 since it's more specific.

**Closed by lenemter** 2023-08-17 11:15 UTC
